### PR TITLE
added config option to enable/disable logging

### PR DESCRIPTION
**Pull request by tbreedveld**
I added an option to enable/disable the soap logging via the admin panel (system -> configuration -> advanced -> developer -> log -> Soap logging Enabled). Perhaps you consider it usefull.

Thnx for providing the soap logger module!

### CODE REVIEW

**Comment by 7ochem** [comment]
+1 This would also great to be in the module. @tbreedveld could you update your PR to solve the merge conflict?

**Comment by tbreedveld** [comment]
done!

**Comment by 7ochem** [comment]
@Marko-M this works like a charm! Could you please merge this?

**Comment by 7ochem** [comment]
@Marko-M, could you merge this one into master?

**Comment by Marko-M** [comment]
Hi all,
merged. Big thanks to @tbreedveld.

Regards

**Pull request merged**
